WRITE [(u2,99)]
WRITE [(t4,46)]
WAIT 3000
DELETE [t4]
WRITE [(k0,73)(j7,12)(k0,73)]
WRITE [(d1,46)(q2,2)(b0,85)]
WRITE [(h7,38)(z9,80)]
READ [j7]
BACKUP
WRITE [(v6,23)]
WRITE [(l0,85)]
WRITE [(s3,47)(x6,83)(d4,9)]
WRITE [(f9,70)]
READ [k0]
SHOW
WRITE [(q7,7)(e1,93)(k6,76)]
WRITE [(g0,54)]
WRITE [(l8,73)(l8,41)(h9,41)(c8,41)]
SHOW
WRITE [(y2,25)]
WRITE [(v2,62)(j0,19)(g8,22)]
READ [b0]
WRITE [(n6,8)]
WAIT 3000
WRITE [(l1,4)(q4,94)]
READ [d4]
READ [l1]
WRITE [(y1,11)(l4,93)(p3,90)(o5,89)]
WRITE [(l5,17)(c2,82)(l6,54)(y5,43)(g9,74)]
SHOW
WRITE [(m1,96)(b2,41)(u4,4)(r4,30)(v7,54)]
WRITE [(b7,43)(o9,42)]
BACKUP
WRITE [(n5,19)]
DELETE [m1]
WRITE [(f1,77)(q8,69)(r6,35)]
READ [r4]
WRITE [(d8,63)(s0,3)]
DELETE [l8,s3,k0,g0]
READ [c2]
WAIT 2000
DELETE [z9,x6,y5,j7,f9]
WRITE [(t2,66)(w8,87)]
